name: Deploy Hello Test

on:
  push:
    branches: [ "win" ]

jobs:
  deploy:
    runs-on: [self-hosted, will-hello]

    steps:
      - name: Descargar código
        uses: actions/checkout@v4
        with:
          path: .

      - name: Crear directorio si no existe
        run: mkdir -p /opt/docker/ic/hello-test

      - name: Limpiar deploy anterior
        run: rm -rf /opt/docker/ic/hello-test/*

      - name: Copiar archivos del proyecto
        run: cp -r ./* /opt/docker/ic/hello-test/
      - name: Reconstruir contenedor
        run: |
          cd /opt/docker/ic/hello-test
          docker rm -f hello-test || true
          docker build -t hello-test-img .
          docker run -d -p 97:80 --name hello-test hello-test-img
          