name: Deploy Hello Test

on:
  push:
    branches: [ "win" ]

jobs:
  deploy:
    runs-on: [self-hosted, win-hello]

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install

      - name: Construir proyecto
        run: npm run build

      - name: Crear directorio si no existe
        run: mkdir -p /opt/docker/hello-test

      - name: Limpiar deploy anterior
        run: rm -rf /opt/docker/hello-test/*

      - name: Copiar build al servidor
        run: cp -r ./dist/* /opt/docker/hello-test/
